version: '3.9'

services:
  wimi:
    container_name:           wimi
    image:                    nginxinc/nginx-unprivileged:stable-alpine3.18-slim
    restart:                  unless-stopped
    logging:
      options:
        max-size:             10m
        max-file:             "3"
    ports:
      - 8080:8080
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

