version: '3.9'

services:
  wimi:
    container_name:           wimi
    build:                    .
    restart:                  unless-stopped
    logging:
      options:
        max-size:             10m
        max-file:             "3"
    ports:
      - 8080:8080
